# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'actionTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_actionTab(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(392, 357)
        Dialog.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.bookButton = QtWidgets.QPushButton(Dialog)
        self.bookButton.setGeometry(QtCore.QRect(100, 130, 181, 51))
        self.bookButton.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.bookButton.setObjectName("pushButton")
        self.checkButton = QtWidgets.QPushButton(Dialog)
        self.checkButton.setGeometry(QtCore.QRect(100, 220, 191, 51))
        self.checkButton.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.checkButton.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 361, 41))
        self.label.setStyleSheet("font: italic 14pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.closeActionTab = QtWidgets.QPushButton(Dialog)
        self.closeActionTab.setGeometry(QtCore.QRect(300, 320, 61, 21))
        self.closeActionTab.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.closeActionTab.setObjectName("closeActionTab")

        self.retranslateUi(Dialog)
        self.closeActionTab.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.bookButton.setText(_translate("Dialog", "Book Appointment"))
        self.checkButton.setText(_translate("Dialog", "Check active appointments"))
        self.label.setText(_translate("Dialog", "Welcome! Choose an action below"))
        self.closeActionTab.setText(_translate("Dialog", "Close"))
