# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ActiveAppointmentsTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_activeAppointment(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(416, 348)
        Dialog.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.closeAppTab = QtWidgets.QPushButton(Dialog)
        self.closeAppTab.setGeometry(QtCore.QRect(330, 320, 75, 23))
        self.closeAppTab.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.closeAppTab.setObjectName("closeAppTab")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(-140, 30, 591, 41))
        self.label_3.setStyleSheet("font: italic 14pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(25, 101, 371, 201))
        self.listView.setStyleSheet("colour: rgb(0, 0, 0);\n"
"background-color:rgb(255, 255, 255)")
        self.listView.setObjectName("listView")
        self.showButton = QtWidgets.QPushButton(Dialog)
        self.showButton.setGeometry(QtCore.QRect(320, 70, 75, 23))
        self.showButton.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.showButton.setObjectName("showButton")
        self.activeBackButton = QtWidgets.QPushButton(Dialog)
        self.activeBackButton.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.activeBackButton.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.activeBackButton.setObjectName("activeBackButton")

        self.retranslateUi(Dialog)
        self.closeAppTab.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.closeAppTab.setText(_translate("Dialog", "Close"))
        self.label_3.setText(_translate("Dialog", "                                    Active appointments"))
        self.showButton.setText(_translate("Dialog", "Show"))
        self.activeBackButton.setText(_translate("Dialog", "Back"))
