# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appointmentTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_appointmentTab(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 357)
        Dialog.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 40, 191, 31))
        self.label.setStyleSheet("font: italic 14pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.confirmButtonApp = QtWidgets.QPushButton(Dialog)
        self.confirmButtonApp.setGeometry(QtCore.QRect(280, 280, 61, 21))
        self.confirmButtonApp.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.confirmButtonApp.setObjectName("confirmButtonApp")
        self.backButton = QtWidgets.QPushButton(Dialog)
        self.backButton.setGeometry(QtCore.QRect(20, 10, 51, 21))
        self.backButton.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.backButton.setObjectName("backButton")
        self.fnameEdit = QtWidgets.QLineEdit(Dialog)
        self.fnameEdit.setGeometry(QtCore.QRect(140, 90, 161, 31))
        self.fnameEdit.setStyleSheet("color:rgb(255, 255, 255);")
        self.fnameEdit.setObjectName("fnameEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 81, 21))
        self.label_2.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 91, 21))
        self.label_3.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.sNameEdit = QtWidgets.QLineEdit(Dialog)
        self.sNameEdit.setGeometry(QtCore.QRect(140, 140, 161, 31))
        self.sNameEdit.setStyleSheet("color:rgb(255, 255, 255);")
        self.sNameEdit.setObjectName("sNameEdit")
        self.reasonComboBox = QtWidgets.QComboBox(Dialog)
        self.reasonComboBox.setGeometry(QtCore.QRect(140, 190, 161, 31))
        self.reasonComboBox.setStyleSheet("color:rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.reasonComboBox.setObjectName("reasonComboBox")
        self.reasonComboBox.addItem("")
        self.reasonComboBox.setItemText(0, "")
        self.reasonComboBox.addItem("")
        self.reasonComboBox.addItem("")
        self.reasonComboBox.addItem("")
        self.reasonComboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 91, 20))
        self.label_4.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.bookingStatusLabel = QtWidgets.QLabel(Dialog)
        self.bookingStatusLabel.setGeometry(QtCore.QRect(30, 320, 261, 21))
        self.bookingStatusLabel.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.bookingStatusLabel.setObjectName("bookingStatusLabel")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(140, 240, 161, 31))
        self.dateEdit.setStyleSheet("color:rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 240, 91, 21))
        self.label_5.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Book appointment"))
        self.confirmButtonApp.setText(_translate("Dialog", "Confirm"))
        self.backButton.setText(_translate("Dialog", "Back"))
        self.label_2.setText(_translate("Dialog", "First Name"))
        self.label_3.setText(_translate("Dialog", "Last name"))
        self.reasonComboBox.setItemText(1, _translate("Dialog", "Enrolling"))
        self.reasonComboBox.setItemText(2, _translate("Dialog", "Marks "))
        self.reasonComboBox.setItemText(3, _translate("Dialog", "Extra lessons"))
        self.reasonComboBox.setItemText(4, _translate("Dialog", "General enquiry"))
        self.label_4.setText(_translate("Dialog", "Reason"))
        self.bookingStatusLabel.setText(_translate("Dialog", "Status:"))
        self.label_5.setText(_translate("Dialog", "Date"))
