# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginPage(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(413, 357)
        Dialog.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.loginButton = QtWidgets.QPushButton(Dialog)
        self.loginButton.setGeometry(QtCore.QRect(90, 200, 81, 31))
        self.loginButton.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(-50, 0, 461, 41))
        self.label_3.setStyleSheet("font: italic 14pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(224, 200, 81, 31))
        self.cancelButton.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius:5px solid rgb(255, 0, 0);\n"
"")
        self.cancelButton.setObjectName("cancelButton")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(90, 70, 211, 111))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.usernameEdit = QtWidgets.QLineEdit(self.splitter)
        self.usernameEdit.setStyleSheet("color:rgb(255, 255, 255);")
        self.usernameEdit.setObjectName("usernameEdit")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setStyleSheet("font: 10pt \"MS Reference Sans Serif\";\n"
"color:rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.passwordEdit = QtWidgets.QLineEdit(self.splitter)
        self.passwordEdit.setStyleSheet("color:rgb(255, 255, 255);")
        self.passwordEdit.setObjectName("passwordEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loginButton.setText(_translate("Dialog", "Login"))
        self.label_3.setText(_translate("Dialog", "                           WELCOME"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_2.setText(_translate("Dialog", "Password"))
